[project]
name = "polylineapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "folium>=0.20.0",
    "polyline>=2.0.3",
    "streamlit>=1.51.0",
    "streamlit-folium>=0.25.3",
]
